development:
  adapter: postgresql
  encoding: unicode
  database: new_recipe
  pool: 5
  host: localhost
  username: postgres
  password: kl;'

test:
  adapter: postgresql
  encoding: unicode
  database: new_recipe_test
  pool: 5
  username: postgres
  password: password

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
